In [51]:
import pandas as pd
import pandas as np

print(pd.Series([1, 2, 3], index=['a', 'b', 'c'])) # with index

a    1
b    2
c    3
dtype: int64

In [3]:
import pandas as pd

series = pd.Series({'a': 1, 'b': 2, 'c':3})
print(series['a'])

1

In [8]:
import pandas as pd

wine_dict = {
    'red_wine': [3, 6, 5],
    'white_wine':[5, 0, 10]
}
sales = pd.DataFrame(wine_dict, index=["adam", "bob", "charles"])
print(sales)
print(sales['white_wine'])

         red_wine  white_wine
adam            3           5
bob             6           0
charles         5          10
adam        5
bob         0
charles    10
Name: white_wine, dtype: int64

In [13]:
import pandas as pd

presidents_df = pd.read_csv('https://sololearn.com/uploads/files/president_heights_party.csv', index_col='name')
presidents_df.shape[1] #number of columns
# print(presidents_df.shape)

4

In [15]:
#Inspecting Head
presidents_df.head(n=3)

                   order  age  height                  party
name
George Washington      1   57     189                   none
John Adams             2   61     170             federalist
Thomas Jefferson       3   57     189  democratic-republican

In [17]:
presidents_df.tail(n=2)

                 order  age  height       party
name
Barack Obama        44   47     185  democratic
Donald J. Trump     45   70     191  republican

In [18]:
#info of DF
presidents_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, George Washington to Donald J. Trump
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   order   45 non-null     int64
 1   age     45 non-null     int64
 2   height  45 non-null     int64
 3   party   45 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.8+ KB

In [19]:
#Info of indicated
print(presidents_df.loc['Abraham Lincoln'])

order             16
age               52
height           193
party     republican
Name: Abraham Lincoln, dtype: object

In [20]:
print(type(presidents_df.loc['Abraham Lincoln']))
print(presidents_df.loc['Abraham Lincoln'].shape)

<class 'pandas.core.series.Series'>
(4,)

In [21]:
#slicing
print(presidents_df.loc['Abraham Lincoln':'Ulysses S. Grant'])

                  order  age  height           party
name
Abraham Lincoln      16   52     193      republican
Andrew Johnson       17   56     178  national union
Ulysses S. Grant     18   46     173      republican

In [22]:
#locate using index position
print(presidents_df.iloc[15:18])

                  order  age  height           party
name
Abraham Lincoln      16   52     193      republican
Andrew Johnson       17   56     178  national union
Ulysses S. Grant     18   46     173      republican

In [25]:
presidents_df.columns

Index(['order', 'age', 'height', 'party'], dtype='object')

In [26]:
presidents_df['age'].shape

(45,)

In [30]:
print(presidents_df[['height','age']].head(n=3))

                   height  age
name
George Washington     189   57
John Adams            170   61
Thomas Jefferson      189   57

In [31]:
print(presidents_df.loc[:, 'order':'height'].head(n=3))

                   order  age  height
name
George Washington      1   57     189
John Adams             2   61     170
Thomas Jefferson       3   57     189

In [70]:
# presidents_arr = np.array(presidents_df['age'])
presidents_arr = pd.Series(presidents_df['age'])
presidents_arr.std()

6.59545297913646

In [72]:
presidents_arr.describe()

count    45.000000
mean     55.000000
std       6.595453
min      42.000000
25%      51.000000
50%      55.000000
75%      58.000000
max      70.000000
Name: age, dtype: float64

In [82]:
presidents_df = pd.read_csv('https://sololearn.com/uploads/files/president_heights_party.csv', index_col='name')
                                  
print(presidents_df.groupby('party').mean())

                           order        age      height
party
democratic             26.066667  52.600000  181.066667
democratic-republican   4.500000  57.250000  176.500000
federalist              2.000000  61.000000  170.000000
national union         17.000000  56.000000  178.000000
none                    1.000000  57.000000  189.000000
republican             29.631579  55.263158  180.894737
whig                   11.000000  58.250000  176.000000

In [77]:
presidents_df.head(n=5)

                   order  age  height                  party
name
George Washington      1   57     189                   none
John Adams             2   61     170             federalist
Thomas Jefferson       3   57     189  democratic-republican
James Madison          4   57     163  democratic-republican
James Monroe           5   58     183  democratic-republican

In [80]:
print(presidents_df.groupby('party').mean())

                           order        age      height
party
democratic             26.066667  52.600000  181.066667
democratic-republican   4.500000  57.250000  176.500000
federalist              2.000000  61.000000  170.000000
national union         17.000000  56.000000  178.000000
none                    1.000000  57.000000  189.000000
republican             29.631579  55.263158  180.894737
whig                   11.000000  58.250000  176.000000

In [84]:
import numpy as np
print(presidents_df.groupby('party').agg({'height': [np.median, np.mean], 'age':    [min, max]}))

                      height             age
                      median        mean min max
party
democratic             180.0  181.066667  43  65
democratic-republican  177.0  176.500000  57  58
federalist             170.0  170.000000  61  61
national union         178.0  178.000000  56  56
none                   189.0  189.000000  57  57
republican             182.0  180.894737  42  70
whig                   174.0  176.000000  50  68

/tmp/ipykernel_352931/678536269.py:2: FutureWarning: The provided callable <function median at 0x7f822409c040> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  print(presidents_df.groupby('party').agg({'height': [np.median, np.mean], 'age':    [min, max]}))
/tmp/ipykernel_352931/678536269.py:2: FutureWarning: The provided callable <function mean at 0x7f822416dc60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(presidents_df.groupby('party').agg({'height': [np.median, np.mean], 'age':    [min, max]}))
/tmp/ipykernel_352931/678536269.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  print(presidents_df.groupby('party').agg({'height': [np.median, np.mean], 'age':    [min, max]}))
/tmp/ipykernel_352931/678536269.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  print(presidents_df.groupby('party').agg({'height': [np.median, np.mean], 'age':    [min, max]}))

In [88]:
presidents_df.groupby('party')['age'].agg([np.median, np.max])

/tmp/ipykernel_352931/945022331.py:1: FutureWarning: The provided callable <function median at 0x7f822409c040> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  presidents_df.groupby('party')['age'].agg([np.median, np.max])
/tmp/ipykernel_352931/945022331.py:1: FutureWarning: The provided callable <function max at 0x7f822416d260> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  presidents_df.groupby('party')['age'].agg([np.median, np.max])

                       median  max
party
democratic               52.0   65
democratic-republican    57.0   58
federalist               61.0   61
national union           56.0   56
none                     57.0   57
republican               54.0   70
whig                     57.5   68

In [92]:
presidents_df.loc['Franklin D. Roosevelt', ['age', 'height', 'party']]

age               51
height           188
party     democratic
Name: Franklin D. Roosevelt, dtype: object

In [99]:
import numpy as np

r = int(input())
num = [float(x) for x in input().split()]

# Convert to numpy array
arr = np.array(num)

# Reshape the array into r rows
reshaped_arr = arr.reshape(r, -1)

# Round to 2 decimal places
rounded_arr = np.round(reshaped_arr, 2)

print(rounded_arr)

 2
 1 2 3 4 5 6

[[1. 2. 3. 2.]
 [2. 3. 3. 2.]]